# Generated by Django 5.2.2 on 2025-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalground',
            name='groundName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='futsalground',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
