# Generated by Django 5.2.2 on 2025-09-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_futsalground_groundname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsalground',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
