# Generated by Django 5.2.2 on 2025-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_futsalground_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='futsalground',
            options={'ordering': ['groundName']},
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='futsalground',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grounds/'),
        ),
        migrations.AlterField(
            model_name='futsalground',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('ground', 'booking_date', 'start_time')},
        ),
    ]
